# Generated by Django 4.2.1 on 2023-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="table",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
