# Generated by Django 4.2.1 on 2023-05-07 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_remove_booking_name_booking_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="MenuItem",
        ),
    ]
